// <auto-generated />
namespace EJ02.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IListtoListTelefonos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IListtoListTelefonos));
        
        string IMigrationMetadata.Id
        {
            get { return "201512122203480_IList to List Telefonos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
